/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.january.geometry.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.january.geometry.xtext.services.IGESGrammarAccess;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class IGESSyntacticSequencer extends AbstractSyntacticSequencer {

	protected IGESGrammarAccess grammarAccess;
	protected AbstractElementAlias match_End_WSTerminalRuleCall_10_q;
	protected AbstractElementAlias match_End_WSTerminalRuleCall_14_q;
	protected AbstractElementAlias match_End_WSTerminalRuleCall_1_q;
	protected AbstractElementAlias match_End_WSTerminalRuleCall_4_q;
	protected AbstractElementAlias match_End_WSTerminalRuleCall_7_q;
	protected AbstractElementAlias match_Entry_INTTerminalRuleCall_15_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_10_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_12_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_14_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_16_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_19_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_22_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_24_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_26_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_28_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_2_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_30_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_32_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_34_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_37_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_4_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_6_q;
	protected AbstractElementAlias match_Entry_WSTerminalRuleCall_8_q;
	protected AbstractElementAlias match_Global_WSTerminalRuleCall_4_q;
	protected AbstractElementAlias match_Global_WSTerminalRuleCall_6_q;
	protected AbstractElementAlias match_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__a;
	protected AbstractElementAlias match_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__p;
	protected AbstractElementAlias match_HString_DELIMITERTerminalRuleCall_0_q;
	protected AbstractElementAlias match_HString_DELIMITERTerminalRuleCall_2_q;
	protected AbstractElementAlias match_PEntry_WSTerminalRuleCall_3_q;
	protected AbstractElementAlias match_PEntry_WSTerminalRuleCall_6_q;
	protected AbstractElementAlias match_PMultiEntry_WSTerminalRuleCall_0_1_q;
	protected AbstractElementAlias match_PMultiEntry_WSTerminalRuleCall_0_4_q;
	protected AbstractElementAlias match_PMultiEntry_WSTerminalRuleCall_3_q;
	protected AbstractElementAlias match_PMultiEntry_WSTerminalRuleCall_6_q;
	protected AbstractElementAlias match_Param_DELIMITERTerminalRuleCall_0_q;
	protected AbstractElementAlias match_Param_DELIMITERTerminalRuleCall_2_q;
	protected AbstractElementAlias match_Pointer_DELIMITERTerminalRuleCall_0_q;
	protected AbstractElementAlias match_Pointer_DELIMITERTerminalRuleCall_2_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (IGESGrammarAccess) access;
		match_End_WSTerminalRuleCall_10_q = new TokenAlias(false, true, grammarAccess.getEndAccess().getWSTerminalRuleCall_10());
		match_End_WSTerminalRuleCall_14_q = new TokenAlias(false, true, grammarAccess.getEndAccess().getWSTerminalRuleCall_14());
		match_End_WSTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getEndAccess().getWSTerminalRuleCall_1());
		match_End_WSTerminalRuleCall_4_q = new TokenAlias(false, true, grammarAccess.getEndAccess().getWSTerminalRuleCall_4());
		match_End_WSTerminalRuleCall_7_q = new TokenAlias(false, true, grammarAccess.getEndAccess().getWSTerminalRuleCall_7());
		match_Entry_INTTerminalRuleCall_15_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getINTTerminalRuleCall_15());
		match_Entry_WSTerminalRuleCall_10_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_10());
		match_Entry_WSTerminalRuleCall_12_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_12());
		match_Entry_WSTerminalRuleCall_14_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_14());
		match_Entry_WSTerminalRuleCall_16_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_16());
		match_Entry_WSTerminalRuleCall_19_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_19());
		match_Entry_WSTerminalRuleCall_22_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_22());
		match_Entry_WSTerminalRuleCall_24_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_24());
		match_Entry_WSTerminalRuleCall_26_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_26());
		match_Entry_WSTerminalRuleCall_28_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_28());
		match_Entry_WSTerminalRuleCall_2_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_2());
		match_Entry_WSTerminalRuleCall_30_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_30());
		match_Entry_WSTerminalRuleCall_32_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_32());
		match_Entry_WSTerminalRuleCall_34_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_34());
		match_Entry_WSTerminalRuleCall_37_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_37());
		match_Entry_WSTerminalRuleCall_4_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_4());
		match_Entry_WSTerminalRuleCall_6_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_6());
		match_Entry_WSTerminalRuleCall_8_q = new TokenAlias(false, true, grammarAccess.getEntryAccess().getWSTerminalRuleCall_8());
		match_Global_WSTerminalRuleCall_4_q = new TokenAlias(false, true, grammarAccess.getGlobalAccess().getWSTerminalRuleCall_4());
		match_Global_WSTerminalRuleCall_6_q = new TokenAlias(false, true, grammarAccess.getGlobalAccess().getWSTerminalRuleCall_6());
		match_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__a = new GroupAlias(true, true, new TokenAlias(false, true, grammarAccess.getGlobalAccess().getWSTerminalRuleCall_1_1()), new TokenAlias(false, false, grammarAccess.getGlobalAccess().getGKeyword_1_2()), new TokenAlias(false, true, grammarAccess.getGlobalAccess().getWSTerminalRuleCall_1_3()), new TokenAlias(false, false, grammarAccess.getGlobalAccess().getINTTerminalRuleCall_1_4()), new TokenAlias(false, false, grammarAccess.getGlobalAccess().getENDLINETerminalRuleCall_1_5()));
		match_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__p = new GroupAlias(true, false, new TokenAlias(false, true, grammarAccess.getGlobalAccess().getWSTerminalRuleCall_1_1()), new TokenAlias(false, false, grammarAccess.getGlobalAccess().getGKeyword_1_2()), new TokenAlias(false, true, grammarAccess.getGlobalAccess().getWSTerminalRuleCall_1_3()), new TokenAlias(false, false, grammarAccess.getGlobalAccess().getINTTerminalRuleCall_1_4()), new TokenAlias(false, false, grammarAccess.getGlobalAccess().getENDLINETerminalRuleCall_1_5()));
		match_HString_DELIMITERTerminalRuleCall_0_q = new TokenAlias(false, true, grammarAccess.getHStringAccess().getDELIMITERTerminalRuleCall_0());
		match_HString_DELIMITERTerminalRuleCall_2_q = new TokenAlias(false, true, grammarAccess.getHStringAccess().getDELIMITERTerminalRuleCall_2());
		match_PEntry_WSTerminalRuleCall_3_q = new TokenAlias(false, true, grammarAccess.getPEntryAccess().getWSTerminalRuleCall_3());
		match_PEntry_WSTerminalRuleCall_6_q = new TokenAlias(false, true, grammarAccess.getPEntryAccess().getWSTerminalRuleCall_6());
		match_PMultiEntry_WSTerminalRuleCall_0_1_q = new TokenAlias(false, true, grammarAccess.getPMultiEntryAccess().getWSTerminalRuleCall_0_1());
		match_PMultiEntry_WSTerminalRuleCall_0_4_q = new TokenAlias(false, true, grammarAccess.getPMultiEntryAccess().getWSTerminalRuleCall_0_4());
		match_PMultiEntry_WSTerminalRuleCall_3_q = new TokenAlias(false, true, grammarAccess.getPMultiEntryAccess().getWSTerminalRuleCall_3());
		match_PMultiEntry_WSTerminalRuleCall_6_q = new TokenAlias(false, true, grammarAccess.getPMultiEntryAccess().getWSTerminalRuleCall_6());
		match_Param_DELIMITERTerminalRuleCall_0_q = new TokenAlias(false, true, grammarAccess.getParamAccess().getDELIMITERTerminalRuleCall_0());
		match_Param_DELIMITERTerminalRuleCall_2_q = new TokenAlias(false, true, grammarAccess.getParamAccess().getDELIMITERTerminalRuleCall_2());
		match_Pointer_DELIMITERTerminalRuleCall_0_q = new TokenAlias(false, true, grammarAccess.getPointerAccess().getDELIMITERTerminalRuleCall_0());
		match_Pointer_DELIMITERTerminalRuleCall_2_q = new TokenAlias(false, true, grammarAccess.getPointerAccess().getDELIMITERTerminalRuleCall_2());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getDELIMITERRule())
			return getDELIMITERToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getENDLINERule())
			return getENDLINEToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getINTRule())
			return getINTToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSEPARATERRule())
			return getSEPARATERToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getWSRule())
			return getWSToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal DELIMITER:
	 * 	','	;
	 */
	protected String getDELIMITERToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ",";
	}
	
	/**
	 * terminal ENDLINE:
	 * 	'\r'? '\n';
	 */
	protected String getENDLINEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\n";
	}
	
	/**
	 * terminal INT returns ecore::EInt:
	 * 	('0'..'9')+;
	 */
	protected String getINTToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * terminal SEPARATER:
	 * 	';' ;
	 */
	protected String getSEPARATERToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ";";
	}
	
	/**
	 * terminal WS:
	 * 	(' ' | '\t' | '\r')+;
	 */
	protected String getWSToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return " ";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_End_WSTerminalRuleCall_10_q.equals(syntax))
				emit_End_WSTerminalRuleCall_10_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_End_WSTerminalRuleCall_14_q.equals(syntax))
				emit_End_WSTerminalRuleCall_14_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_End_WSTerminalRuleCall_1_q.equals(syntax))
				emit_End_WSTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_End_WSTerminalRuleCall_4_q.equals(syntax))
				emit_End_WSTerminalRuleCall_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_End_WSTerminalRuleCall_7_q.equals(syntax))
				emit_End_WSTerminalRuleCall_7_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_INTTerminalRuleCall_15_q.equals(syntax))
				emit_Entry_INTTerminalRuleCall_15_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_10_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_10_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_12_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_12_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_14_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_14_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_16_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_16_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_19_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_19_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_22_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_22_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_24_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_24_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_26_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_26_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_28_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_28_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_2_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_30_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_30_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_32_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_32_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_34_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_34_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_37_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_37_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_4_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_6_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entry_WSTerminalRuleCall_8_q.equals(syntax))
				emit_Entry_WSTerminalRuleCall_8_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Global_WSTerminalRuleCall_4_q.equals(syntax))
				emit_Global_WSTerminalRuleCall_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Global_WSTerminalRuleCall_6_q.equals(syntax))
				emit_Global_WSTerminalRuleCall_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__a.equals(syntax))
				emit_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__p.equals(syntax))
				emit_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HString_DELIMITERTerminalRuleCall_0_q.equals(syntax))
				emit_HString_DELIMITERTerminalRuleCall_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HString_DELIMITERTerminalRuleCall_2_q.equals(syntax))
				emit_HString_DELIMITERTerminalRuleCall_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PEntry_WSTerminalRuleCall_3_q.equals(syntax))
				emit_PEntry_WSTerminalRuleCall_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PEntry_WSTerminalRuleCall_6_q.equals(syntax))
				emit_PEntry_WSTerminalRuleCall_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PMultiEntry_WSTerminalRuleCall_0_1_q.equals(syntax))
				emit_PMultiEntry_WSTerminalRuleCall_0_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PMultiEntry_WSTerminalRuleCall_0_4_q.equals(syntax))
				emit_PMultiEntry_WSTerminalRuleCall_0_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PMultiEntry_WSTerminalRuleCall_3_q.equals(syntax))
				emit_PMultiEntry_WSTerminalRuleCall_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PMultiEntry_WSTerminalRuleCall_6_q.equals(syntax))
				emit_PMultiEntry_WSTerminalRuleCall_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Param_DELIMITERTerminalRuleCall_0_q.equals(syntax))
				emit_Param_DELIMITERTerminalRuleCall_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Param_DELIMITERTerminalRuleCall_2_q.equals(syntax))
				emit_Param_DELIMITERTerminalRuleCall_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pointer_DELIMITERTerminalRuleCall_0_q.equals(syntax))
				emit_Pointer_DELIMITERTerminalRuleCall_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pointer_DELIMITERTerminalRuleCall_2_q.equals(syntax))
				emit_Pointer_DELIMITERTerminalRuleCall_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     dval=INT 'P' (ambiguity) pval=INT
	 */
	protected void emit_End_WSTerminalRuleCall_10_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     pval=INT WS 'T' (ambiguity) tval=INT
	 */
	protected void emit_End_WSTerminalRuleCall_14_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'S' (ambiguity) sval=INT
	 */
	protected void emit_End_WSTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     sval=INT 'G' (ambiguity) gval=INT
	 */
	protected void emit_End_WSTerminalRuleCall_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     gval=INT 'D' (ambiguity) dval=INT
	 */
	protected void emit_End_WSTerminalRuleCall_7_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     INT?
	 *
	 * This ambiguous syntax occurs at:
	 *     TransformMatrix=INT WS? (ambiguity) WS? status=INT
	 */
	protected void emit_Entry_INTTerminalRuleCall_15_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     level=INT (ambiguity) view=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_10_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     view=INT (ambiguity) TransformMatrix=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_12_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     TransformMatrix=INT (ambiguity) INT? WS? status=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_14_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     TransformMatrix=INT WS? INT? (ambiguity) status=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_16_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     status=INT 'D' (ambiguity) index=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_19_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     index=INT ENDLINE (ambiguity) INT WS? lineWeight=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_22_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     index=INT ENDLINE WS? INT (ambiguity) lineWeight=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_24_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     lineWeight=INT (ambiguity) color=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_26_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     color=INT (ambiguity) paramLines=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_28_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=INT (ambiguity) paramData=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     paramLines=INT (ambiguity) form=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_30_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     form=INT (ambiguity) WS? subNum=INT
	 *     form=INT (ambiguity) entityLabel=STRING
	 */
	protected void emit_Entry_WSTerminalRuleCall_32_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     entityLabel=STRING (ambiguity) subNum=INT
	 *     form=INT WS? (ambiguity) subNum=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_34_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     subNum=INT 'D' (ambiguity) INT ENDLINE (rule end)
	 */
	protected void emit_Entry_WSTerminalRuleCall_37_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     paramData=INT (ambiguity) structure=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     structure=INT (ambiguity) lineFont=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     lineFont=INT (ambiguity) level=INT
	 */
	protected void emit_Entry_WSTerminalRuleCall_8_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (WS? 'G' WS? INT ENDLINE)+ SEPARATER (ambiguity) 'G' WS? INT ENDLINE (rule start)
	 *     values+=Value (WS? 'G' WS? INT ENDLINE)+ SEPARATER (ambiguity) 'G' WS? INT ENDLINE (rule end)
	 *     values+=Value SEPARATER (ambiguity) 'G' WS? INT ENDLINE (rule end)
	 */
	protected void emit_Global_WSTerminalRuleCall_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (WS? 'G' WS? INT ENDLINE)+ SEPARATER WS? 'G' (ambiguity) INT ENDLINE (rule start)
	 *     values+=Value (WS? 'G' WS? INT ENDLINE)+ SEPARATER WS? 'G' (ambiguity) INT ENDLINE (rule end)
	 *     values+=Value SEPARATER WS? 'G' (ambiguity) INT ENDLINE (rule end)
	 */
	protected void emit_Global_WSTerminalRuleCall_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (WS? 'G' WS? INT ENDLINE)*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) values+=Value
	 *     values+=Value (ambiguity) values+=Value
	 */
	protected void emit_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (WS? 'G' WS? INT ENDLINE)+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) SEPARATER WS? 'G' WS? INT ENDLINE (rule start)
	 *     (rule start) (ambiguity) values+=Value
	 *     values+=Value (ambiguity) SEPARATER WS? 'G' WS? INT ENDLINE (rule end)
	 *     values+=Value (ambiguity) values+=Value
	 */
	protected void emit_Global___WSTerminalRuleCall_1_1_q_GKeyword_1_2_WSTerminalRuleCall_1_3_q_INTTerminalRuleCall_1_4_ENDLINETerminalRuleCall_1_5__p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     DELIMITER?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) val=HOLLERITH
	 */
	protected void emit_HString_DELIMITERTerminalRuleCall_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     DELIMITER?
	 *
	 * This ambiguous syntax occurs at:
	 *     val=HOLLERITH (ambiguity) (rule end)
	 */
	protected void emit_HString_DELIMITERTerminalRuleCall_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=INT SEPARATER (ambiguity) dIndex=INT
	 *     values+=Value SEPARATER (ambiguity) dIndex=INT
	 */
	protected void emit_PEntry_WSTerminalRuleCall_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     dIndex=INT 'P' (ambiguity) indicies+=INT
	 */
	protected void emit_PEntry_WSTerminalRuleCall_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) dIndex=INT
	 *     indicies+=INT ENDLINE (ambiguity) dIndex=INT
	 *     values+=Value (ambiguity) dIndex=INT
	 */
	protected void emit_PMultiEntry_WSTerminalRuleCall_0_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     dIndex=INT 'P' (ambiguity) indicies+=INT
	 */
	protected void emit_PMultiEntry_WSTerminalRuleCall_0_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     indicies+=INT ENDLINE SEPARATER (ambiguity) INT 'P' WS? INT ENDLINE (rule end)
	 *     values+=Value SEPARATER (ambiguity) INT 'P' WS? INT ENDLINE (rule end)
	 */
	protected void emit_PMultiEntry_WSTerminalRuleCall_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     WS?
	 *
	 * This ambiguous syntax occurs at:
	 *     indicies+=INT ENDLINE SEPARATER WS? INT 'P' (ambiguity) INT ENDLINE (rule end)
	 *     values+=Value SEPARATER WS? INT 'P' (ambiguity) INT ENDLINE (rule end)
	 */
	protected void emit_PMultiEntry_WSTerminalRuleCall_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     DELIMITER?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) val=DOUBLE
	 */
	protected void emit_Param_DELIMITERTerminalRuleCall_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     DELIMITER?
	 *
	 * This ambiguous syntax occurs at:
	 *     val=DOUBLE (ambiguity) (rule end)
	 */
	protected void emit_Param_DELIMITERTerminalRuleCall_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     DELIMITER?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) val=INT
	 */
	protected void emit_Pointer_DELIMITERTerminalRuleCall_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     DELIMITER?
	 *
	 * This ambiguous syntax occurs at:
	 *     val=INT (ambiguity) (rule end)
	 */
	protected void emit_Pointer_DELIMITERTerminalRuleCall_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
