/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.january.geometry.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class IGESGrammarAccess extends AbstractGrammarElementFinder {
	
	public class IGESElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.IGES");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStartAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStartStartParserRuleCall_0_0 = (RuleCall)cStartAssignment_0.eContents().get(0);
		private final Assignment cGlobalAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cGlobalGlobalParserRuleCall_1_0 = (RuleCall)cGlobalAssignment_1.eContents().get(0);
		private final Assignment cDataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDataDataParserRuleCall_2_0 = (RuleCall)cDataAssignment_2.eContents().get(0);
		private final Assignment cParametersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParametersParametersParserRuleCall_3_0 = (RuleCall)cParametersAssignment_3.eContents().get(0);
		private final Assignment cEndAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEndEndParserRuleCall_4_0 = (RuleCall)cEndAssignment_4.eContents().get(0);
		
		//IGES:
		//	start=Start
		//	global=Global
		//	data=Data
		//	parameters=Parameters
		//	end=End;
		@Override public ParserRule getRule() { return rule; }
		
		//start=Start global=Global data=Data parameters=Parameters end=End
		public Group getGroup() { return cGroup; }
		
		//start=Start
		public Assignment getStartAssignment_0() { return cStartAssignment_0; }
		
		//Start
		public RuleCall getStartStartParserRuleCall_0_0() { return cStartStartParserRuleCall_0_0; }
		
		//global=Global
		public Assignment getGlobalAssignment_1() { return cGlobalAssignment_1; }
		
		//Global
		public RuleCall getGlobalGlobalParserRuleCall_1_0() { return cGlobalGlobalParserRuleCall_1_0; }
		
		//data=Data
		public Assignment getDataAssignment_2() { return cDataAssignment_2; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_2_0() { return cDataDataParserRuleCall_2_0; }
		
		//parameters=Parameters
		public Assignment getParametersAssignment_3() { return cParametersAssignment_3; }
		
		//Parameters
		public RuleCall getParametersParametersParserRuleCall_3_0() { return cParametersParametersParserRuleCall_3_0; }
		
		//end=End
		public Assignment getEndAssignment_4() { return cEndAssignment_4; }
		
		//End
		public RuleCall getEndEndParserRuleCall_4_0() { return cEndEndParserRuleCall_4_0; }
	}
	public class StartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Start");
		private final Assignment cLinesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLinesStartLineParserRuleCall_0 = (RuleCall)cLinesAssignment.eContents().get(0);
		
		//Start:
		//	lines+=startLine+;
		@Override public ParserRule getRule() { return rule; }
		
		//lines+=startLine+
		public Assignment getLinesAssignment() { return cLinesAssignment; }
		
		//startLine
		public RuleCall getLinesStartLineParserRuleCall_0() { return cLinesStartLineParserRuleCall_0; }
	}
	public class GlobalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Global");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGlobalAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cValuesAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cValuesValueParserRuleCall_1_0_0 = (RuleCall)cValuesAssignment_1_0.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cGKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final RuleCall cWSTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_1_4 = (RuleCall)cGroup_1.eContents().get(4);
		private final RuleCall cENDLINETerminalRuleCall_1_5 = (RuleCall)cGroup_1.eContents().get(5);
		private final Assignment cValuesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValuesValueParserRuleCall_2_0 = (RuleCall)cValuesAssignment_2.eContents().get(0);
		private final RuleCall cSEPARATERTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cWSTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Keyword cGKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final RuleCall cWSTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final RuleCall cINTTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final RuleCall cENDLINETerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		
		//Global:
		//	{Global} (values+=Value* WS? 'G' WS? INT ENDLINE)+
		//	values+=Value* SEPARATER WS? 'G' WS? INT ENDLINE;
		@Override public ParserRule getRule() { return rule; }
		
		//{Global} (values+=Value* WS? 'G' WS? INT ENDLINE)+ values+=Value* SEPARATER WS? 'G' WS? INT ENDLINE
		public Group getGroup() { return cGroup; }
		
		//{Global}
		public Action getGlobalAction_0() { return cGlobalAction_0; }
		
		//(values+=Value* WS? 'G' WS? INT ENDLINE)+
		public Group getGroup_1() { return cGroup_1; }
		
		//values+=Value*
		public Assignment getValuesAssignment_1_0() { return cValuesAssignment_1_0; }
		
		//Value
		public RuleCall getValuesValueParserRuleCall_1_0_0() { return cValuesValueParserRuleCall_1_0_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_1_1() { return cWSTerminalRuleCall_1_1; }
		
		//'G'
		public Keyword getGKeyword_1_2() { return cGKeyword_1_2; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_1_3() { return cWSTerminalRuleCall_1_3; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_4() { return cINTTerminalRuleCall_1_4; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_1_5() { return cENDLINETerminalRuleCall_1_5; }
		
		//values+=Value*
		public Assignment getValuesAssignment_2() { return cValuesAssignment_2; }
		
		//Value
		public RuleCall getValuesValueParserRuleCall_2_0() { return cValuesValueParserRuleCall_2_0; }
		
		//SEPARATER
		public RuleCall getSEPARATERTerminalRuleCall_3() { return cSEPARATERTerminalRuleCall_3; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_4() { return cWSTerminalRuleCall_4; }
		
		//'G'
		public Keyword getGKeyword_5() { return cGKeyword_5; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_6() { return cWSTerminalRuleCall_6; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_7() { return cINTTerminalRuleCall_7; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_8() { return cENDLINETerminalRuleCall_8; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Data");
		private final Assignment cEntriesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cEntriesEntryParserRuleCall_0 = (RuleCall)cEntriesAssignment.eContents().get(0);
		
		//Data:
		//	entries+=Entry+;
		@Override public ParserRule getRule() { return rule; }
		
		//entries+=Entry+
		public Assignment getEntriesAssignment() { return cEntriesAssignment; }
		
		//Entry
		public RuleCall getEntriesEntryParserRuleCall_0() { return cEntriesEntryParserRuleCall_0; }
	}
	public class EntryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Entry");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWSTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeINTTerminalRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cParamDataAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParamDataINTTerminalRuleCall_3_0 = (RuleCall)cParamDataAssignment_3.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cStructureAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStructureINTTerminalRuleCall_5_0 = (RuleCall)cStructureAssignment_5.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cLineFontAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLineFontINTTerminalRuleCall_7_0 = (RuleCall)cLineFontAssignment_7.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final Assignment cLevelAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cLevelINTTerminalRuleCall_9_0 = (RuleCall)cLevelAssignment_9.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		private final Assignment cViewAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cViewINTTerminalRuleCall_11_0 = (RuleCall)cViewAssignment_11.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_12 = (RuleCall)cGroup.eContents().get(12);
		private final Assignment cTransformMatrixAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cTransformMatrixINTTerminalRuleCall_13_0 = (RuleCall)cTransformMatrixAssignment_13.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_14 = (RuleCall)cGroup.eContents().get(14);
		private final RuleCall cINTTerminalRuleCall_15 = (RuleCall)cGroup.eContents().get(15);
		private final RuleCall cWSTerminalRuleCall_16 = (RuleCall)cGroup.eContents().get(16);
		private final Assignment cStatusAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cStatusINTTerminalRuleCall_17_0 = (RuleCall)cStatusAssignment_17.eContents().get(0);
		private final Keyword cDKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final RuleCall cWSTerminalRuleCall_19 = (RuleCall)cGroup.eContents().get(19);
		private final Assignment cIndexAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cIndexINTTerminalRuleCall_20_0 = (RuleCall)cIndexAssignment_20.eContents().get(0);
		private final RuleCall cENDLINETerminalRuleCall_21 = (RuleCall)cGroup.eContents().get(21);
		private final RuleCall cWSTerminalRuleCall_22 = (RuleCall)cGroup.eContents().get(22);
		private final RuleCall cINTTerminalRuleCall_23 = (RuleCall)cGroup.eContents().get(23);
		private final RuleCall cWSTerminalRuleCall_24 = (RuleCall)cGroup.eContents().get(24);
		private final Assignment cLineWeightAssignment_25 = (Assignment)cGroup.eContents().get(25);
		private final RuleCall cLineWeightINTTerminalRuleCall_25_0 = (RuleCall)cLineWeightAssignment_25.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_26 = (RuleCall)cGroup.eContents().get(26);
		private final Assignment cColorAssignment_27 = (Assignment)cGroup.eContents().get(27);
		private final RuleCall cColorINTTerminalRuleCall_27_0 = (RuleCall)cColorAssignment_27.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_28 = (RuleCall)cGroup.eContents().get(28);
		private final Assignment cParamLinesAssignment_29 = (Assignment)cGroup.eContents().get(29);
		private final RuleCall cParamLinesINTTerminalRuleCall_29_0 = (RuleCall)cParamLinesAssignment_29.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_30 = (RuleCall)cGroup.eContents().get(30);
		private final Assignment cFormAssignment_31 = (Assignment)cGroup.eContents().get(31);
		private final RuleCall cFormINTTerminalRuleCall_31_0 = (RuleCall)cFormAssignment_31.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_32 = (RuleCall)cGroup.eContents().get(32);
		private final Assignment cEntityLabelAssignment_33 = (Assignment)cGroup.eContents().get(33);
		private final RuleCall cEntityLabelSTRINGTerminalRuleCall_33_0 = (RuleCall)cEntityLabelAssignment_33.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_34 = (RuleCall)cGroup.eContents().get(34);
		private final Assignment cSubNumAssignment_35 = (Assignment)cGroup.eContents().get(35);
		private final RuleCall cSubNumINTTerminalRuleCall_35_0 = (RuleCall)cSubNumAssignment_35.eContents().get(0);
		private final Keyword cDKeyword_36 = (Keyword)cGroup.eContents().get(36);
		private final RuleCall cWSTerminalRuleCall_37 = (RuleCall)cGroup.eContents().get(37);
		private final RuleCall cINTTerminalRuleCall_38 = (RuleCall)cGroup.eContents().get(38);
		private final RuleCall cENDLINETerminalRuleCall_39 = (RuleCall)cGroup.eContents().get(39);
		
		//Entry:
		//	WS type=INT WS? paramData=INT WS? structure=INT WS? lineFont=INT WS? level=INT WS? view=INT WS? TransformMatrix=INT
		//	WS? INT? WS? status=INT 'D' WS? index=INT ENDLINE
		//	WS? INT WS? lineWeight=INT WS? color=INT WS? paramLines=INT WS? form=INT WS? entityLabel=STRING? WS? subNum=INT 'D'
		//	WS? INT ENDLINE;
		@Override public ParserRule getRule() { return rule; }
		
		//WS type=INT WS? paramData=INT WS? structure=INT WS? lineFont=INT WS? level=INT WS? view=INT WS? TransformMatrix=INT WS?
		//INT? WS? status=INT 'D' WS? index=INT ENDLINE WS? INT WS? lineWeight=INT WS? color=INT WS? paramLines=INT WS? form=INT
		//WS? entityLabel=STRING? WS? subNum=INT 'D' WS? INT ENDLINE
		public Group getGroup() { return cGroup; }
		
		//WS
		public RuleCall getWSTerminalRuleCall_0() { return cWSTerminalRuleCall_0; }
		
		//type=INT
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//INT
		public RuleCall getTypeINTTerminalRuleCall_1_0() { return cTypeINTTerminalRuleCall_1_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_2() { return cWSTerminalRuleCall_2; }
		
		//paramData=INT
		public Assignment getParamDataAssignment_3() { return cParamDataAssignment_3; }
		
		//INT
		public RuleCall getParamDataINTTerminalRuleCall_3_0() { return cParamDataINTTerminalRuleCall_3_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_4() { return cWSTerminalRuleCall_4; }
		
		//structure=INT
		public Assignment getStructureAssignment_5() { return cStructureAssignment_5; }
		
		//INT
		public RuleCall getStructureINTTerminalRuleCall_5_0() { return cStructureINTTerminalRuleCall_5_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_6() { return cWSTerminalRuleCall_6; }
		
		//lineFont=INT
		public Assignment getLineFontAssignment_7() { return cLineFontAssignment_7; }
		
		//INT
		public RuleCall getLineFontINTTerminalRuleCall_7_0() { return cLineFontINTTerminalRuleCall_7_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_8() { return cWSTerminalRuleCall_8; }
		
		//level=INT
		public Assignment getLevelAssignment_9() { return cLevelAssignment_9; }
		
		//INT
		public RuleCall getLevelINTTerminalRuleCall_9_0() { return cLevelINTTerminalRuleCall_9_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_10() { return cWSTerminalRuleCall_10; }
		
		//view=INT
		public Assignment getViewAssignment_11() { return cViewAssignment_11; }
		
		//INT
		public RuleCall getViewINTTerminalRuleCall_11_0() { return cViewINTTerminalRuleCall_11_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_12() { return cWSTerminalRuleCall_12; }
		
		//TransformMatrix=INT
		public Assignment getTransformMatrixAssignment_13() { return cTransformMatrixAssignment_13; }
		
		//INT
		public RuleCall getTransformMatrixINTTerminalRuleCall_13_0() { return cTransformMatrixINTTerminalRuleCall_13_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_14() { return cWSTerminalRuleCall_14; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_15() { return cINTTerminalRuleCall_15; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_16() { return cWSTerminalRuleCall_16; }
		
		//status=INT
		public Assignment getStatusAssignment_17() { return cStatusAssignment_17; }
		
		//INT
		public RuleCall getStatusINTTerminalRuleCall_17_0() { return cStatusINTTerminalRuleCall_17_0; }
		
		//'D'
		public Keyword getDKeyword_18() { return cDKeyword_18; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_19() { return cWSTerminalRuleCall_19; }
		
		//index=INT
		public Assignment getIndexAssignment_20() { return cIndexAssignment_20; }
		
		//INT
		public RuleCall getIndexINTTerminalRuleCall_20_0() { return cIndexINTTerminalRuleCall_20_0; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_21() { return cENDLINETerminalRuleCall_21; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_22() { return cWSTerminalRuleCall_22; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_23() { return cINTTerminalRuleCall_23; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_24() { return cWSTerminalRuleCall_24; }
		
		//lineWeight=INT
		public Assignment getLineWeightAssignment_25() { return cLineWeightAssignment_25; }
		
		//INT
		public RuleCall getLineWeightINTTerminalRuleCall_25_0() { return cLineWeightINTTerminalRuleCall_25_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_26() { return cWSTerminalRuleCall_26; }
		
		//color=INT
		public Assignment getColorAssignment_27() { return cColorAssignment_27; }
		
		//INT
		public RuleCall getColorINTTerminalRuleCall_27_0() { return cColorINTTerminalRuleCall_27_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_28() { return cWSTerminalRuleCall_28; }
		
		//paramLines=INT
		public Assignment getParamLinesAssignment_29() { return cParamLinesAssignment_29; }
		
		//INT
		public RuleCall getParamLinesINTTerminalRuleCall_29_0() { return cParamLinesINTTerminalRuleCall_29_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_30() { return cWSTerminalRuleCall_30; }
		
		//form=INT
		public Assignment getFormAssignment_31() { return cFormAssignment_31; }
		
		//INT
		public RuleCall getFormINTTerminalRuleCall_31_0() { return cFormINTTerminalRuleCall_31_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_32() { return cWSTerminalRuleCall_32; }
		
		//entityLabel=STRING?
		public Assignment getEntityLabelAssignment_33() { return cEntityLabelAssignment_33; }
		
		//STRING
		public RuleCall getEntityLabelSTRINGTerminalRuleCall_33_0() { return cEntityLabelSTRINGTerminalRuleCall_33_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_34() { return cWSTerminalRuleCall_34; }
		
		//subNum=INT
		public Assignment getSubNumAssignment_35() { return cSubNumAssignment_35; }
		
		//INT
		public RuleCall getSubNumINTTerminalRuleCall_35_0() { return cSubNumINTTerminalRuleCall_35_0; }
		
		//'D'
		public Keyword getDKeyword_36() { return cDKeyword_36; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_37() { return cWSTerminalRuleCall_37; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_38() { return cINTTerminalRuleCall_38; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_39() { return cENDLINETerminalRuleCall_39; }
	}
	public class ParametersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Parameters");
		private final Assignment cEntriesAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cEntriesAlternatives_0 = (Alternatives)cEntriesAssignment.eContents().get(0);
		private final RuleCall cEntriesPMultiEntryParserRuleCall_0_0 = (RuleCall)cEntriesAlternatives_0.eContents().get(0);
		private final RuleCall cEntriesPEntryParserRuleCall_0_1 = (RuleCall)cEntriesAlternatives_0.eContents().get(1);
		
		//Parameters:
		//	entries+=(PMultiEntry | PEntry)+;
		@Override public ParserRule getRule() { return rule; }
		
		//entries+=(PMultiEntry | PEntry)+
		public Assignment getEntriesAssignment() { return cEntriesAssignment; }
		
		//(PMultiEntry | PEntry)
		public Alternatives getEntriesAlternatives_0() { return cEntriesAlternatives_0; }
		
		//PMultiEntry
		public RuleCall getEntriesPMultiEntryParserRuleCall_0_0() { return cEntriesPMultiEntryParserRuleCall_0_0; }
		
		//PEntry
		public RuleCall getEntriesPEntryParserRuleCall_0_1() { return cEntriesPEntryParserRuleCall_0_1; }
	}
	public class PEntryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.PEntry");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeINTTerminalRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cValuesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValuesValueParserRuleCall_1_0 = (RuleCall)cValuesAssignment_1.eContents().get(0);
		private final RuleCall cSEPARATERTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cWSTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cDIndexAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDIndexINTTerminalRuleCall_4_0 = (RuleCall)cDIndexAssignment_4.eContents().get(0);
		private final Keyword cPKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final RuleCall cWSTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cIndiciesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cIndiciesINTTerminalRuleCall_7_0 = (RuleCall)cIndiciesAssignment_7.eContents().get(0);
		private final RuleCall cENDLINETerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		
		//PEntry:
		//	type=INT
		//	values+=Value* SEPARATER WS? dIndex=INT 'P' WS? indicies+=INT ENDLINE;
		@Override public ParserRule getRule() { return rule; }
		
		//type=INT values+=Value* SEPARATER WS? dIndex=INT 'P' WS? indicies+=INT ENDLINE
		public Group getGroup() { return cGroup; }
		
		//type=INT
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//INT
		public RuleCall getTypeINTTerminalRuleCall_0_0() { return cTypeINTTerminalRuleCall_0_0; }
		
		//values+=Value*
		public Assignment getValuesAssignment_1() { return cValuesAssignment_1; }
		
		//Value
		public RuleCall getValuesValueParserRuleCall_1_0() { return cValuesValueParserRuleCall_1_0; }
		
		//SEPARATER
		public RuleCall getSEPARATERTerminalRuleCall_2() { return cSEPARATERTerminalRuleCall_2; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_3() { return cWSTerminalRuleCall_3; }
		
		//dIndex=INT
		public Assignment getDIndexAssignment_4() { return cDIndexAssignment_4; }
		
		//INT
		public RuleCall getDIndexINTTerminalRuleCall_4_0() { return cDIndexINTTerminalRuleCall_4_0; }
		
		//'P'
		public Keyword getPKeyword_5() { return cPKeyword_5; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_6() { return cWSTerminalRuleCall_6; }
		
		//indicies+=INT
		public Assignment getIndiciesAssignment_7() { return cIndiciesAssignment_7; }
		
		//INT
		public RuleCall getIndiciesINTTerminalRuleCall_7_0() { return cIndiciesINTTerminalRuleCall_7_0; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_8() { return cENDLINETerminalRuleCall_8; }
	}
	public class PMultiEntryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.PMultiEntry");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cValuesAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cValuesValueParserRuleCall_0_0_0 = (RuleCall)cValuesAssignment_0_0.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Assignment cDIndexAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDIndexINTTerminalRuleCall_0_2_0 = (RuleCall)cDIndexAssignment_0_2.eContents().get(0);
		private final Keyword cPKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final RuleCall cWSTerminalRuleCall_0_4 = (RuleCall)cGroup_0.eContents().get(4);
		private final Assignment cIndiciesAssignment_0_5 = (Assignment)cGroup_0.eContents().get(5);
		private final RuleCall cIndiciesINTTerminalRuleCall_0_5_0 = (RuleCall)cIndiciesAssignment_0_5.eContents().get(0);
		private final RuleCall cENDLINETerminalRuleCall_0_6 = (RuleCall)cGroup_0.eContents().get(6);
		private final Assignment cValuesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValuesValueParserRuleCall_1_0 = (RuleCall)cValuesAssignment_1.eContents().get(0);
		private final RuleCall cSEPARATERTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cWSTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Keyword cPKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final RuleCall cWSTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final RuleCall cINTTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final RuleCall cENDLINETerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		
		//PMultiEntry PEntry:
		//	(values+=Value* WS? dIndex=INT 'P' WS? indicies+=INT ENDLINE)+
		//	values+=Value* SEPARATER WS? INT 'P' WS? INT ENDLINE
		@Override public ParserRule getRule() { return rule; }
		
		//(values+=Value* WS? dIndex=INT 'P' WS? indicies+=INT ENDLINE)+ values+=Value* SEPARATER WS? INT 'P' WS? INT ENDLINE
		public Group getGroup() { return cGroup; }
		
		//(values+=Value* WS? dIndex=INT 'P' WS? indicies+=INT ENDLINE)+
		public Group getGroup_0() { return cGroup_0; }
		
		//values+=Value*
		public Assignment getValuesAssignment_0_0() { return cValuesAssignment_0_0; }
		
		//Value
		public RuleCall getValuesValueParserRuleCall_0_0_0() { return cValuesValueParserRuleCall_0_0_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_0_1() { return cWSTerminalRuleCall_0_1; }
		
		//dIndex=INT
		public Assignment getDIndexAssignment_0_2() { return cDIndexAssignment_0_2; }
		
		//INT
		public RuleCall getDIndexINTTerminalRuleCall_0_2_0() { return cDIndexINTTerminalRuleCall_0_2_0; }
		
		//'P'
		public Keyword getPKeyword_0_3() { return cPKeyword_0_3; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_0_4() { return cWSTerminalRuleCall_0_4; }
		
		//indicies+=INT
		public Assignment getIndiciesAssignment_0_5() { return cIndiciesAssignment_0_5; }
		
		//INT
		public RuleCall getIndiciesINTTerminalRuleCall_0_5_0() { return cIndiciesINTTerminalRuleCall_0_5_0; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_0_6() { return cENDLINETerminalRuleCall_0_6; }
		
		//values+=Value*
		public Assignment getValuesAssignment_1() { return cValuesAssignment_1; }
		
		//Value
		public RuleCall getValuesValueParserRuleCall_1_0() { return cValuesValueParserRuleCall_1_0; }
		
		//SEPARATER
		public RuleCall getSEPARATERTerminalRuleCall_2() { return cSEPARATERTerminalRuleCall_2; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_3() { return cWSTerminalRuleCall_3; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
		
		//'P'
		public Keyword getPKeyword_5() { return cPKeyword_5; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_6() { return cWSTerminalRuleCall_6; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_7() { return cINTTerminalRuleCall_7; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_8() { return cENDLINETerminalRuleCall_8; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cParamParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPointerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cHStringParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Value:
		//	Param | Pointer | HString;
		@Override public ParserRule getRule() { return rule; }
		
		//Param | Pointer | HString
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Param
		public RuleCall getParamParserRuleCall_0() { return cParamParserRuleCall_0; }
		
		//Pointer
		public RuleCall getPointerParserRuleCall_1() { return cPointerParserRuleCall_1; }
		
		//HString
		public RuleCall getHStringParserRuleCall_2() { return cHStringParserRuleCall_2; }
	}
	public class HStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.HString");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDELIMITERTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValHOLLERITHTerminalRuleCall_1_0 = (RuleCall)cValAssignment_1.eContents().get(0);
		private final RuleCall cDELIMITERTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//HString:
		//	DELIMITER? val=HOLLERITH DELIMITER?;
		@Override public ParserRule getRule() { return rule; }
		
		//DELIMITER? val=HOLLERITH DELIMITER?
		public Group getGroup() { return cGroup; }
		
		//DELIMITER?
		public RuleCall getDELIMITERTerminalRuleCall_0() { return cDELIMITERTerminalRuleCall_0; }
		
		//val=HOLLERITH
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//HOLLERITH
		public RuleCall getValHOLLERITHTerminalRuleCall_1_0() { return cValHOLLERITHTerminalRuleCall_1_0; }
		
		//DELIMITER?
		public RuleCall getDELIMITERTerminalRuleCall_2() { return cDELIMITERTerminalRuleCall_2; }
	}
	public class ParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Param");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDELIMITERTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValDOUBLETerminalRuleCall_1_0 = (RuleCall)cValAssignment_1.eContents().get(0);
		private final RuleCall cDELIMITERTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Param:
		//	DELIMITER? val=DOUBLE DELIMITER?;
		@Override public ParserRule getRule() { return rule; }
		
		//DELIMITER? val=DOUBLE DELIMITER?
		public Group getGroup() { return cGroup; }
		
		//DELIMITER?
		public RuleCall getDELIMITERTerminalRuleCall_0() { return cDELIMITERTerminalRuleCall_0; }
		
		//val=DOUBLE
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//DOUBLE
		public RuleCall getValDOUBLETerminalRuleCall_1_0() { return cValDOUBLETerminalRuleCall_1_0; }
		
		//DELIMITER?
		public RuleCall getDELIMITERTerminalRuleCall_2() { return cDELIMITERTerminalRuleCall_2; }
	}
	public class PointerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.Pointer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDELIMITERTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_1_0 = (RuleCall)cValAssignment_1.eContents().get(0);
		private final RuleCall cDELIMITERTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Pointer:
		//	DELIMITER? val=INT DELIMITER?;
		@Override public ParserRule getRule() { return rule; }
		
		//DELIMITER? val=INT DELIMITER?
		public Group getGroup() { return cGroup; }
		
		//DELIMITER?
		public RuleCall getDELIMITERTerminalRuleCall_0() { return cDELIMITERTerminalRuleCall_0; }
		
		//val=INT
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_1_0() { return cValINTTerminalRuleCall_1_0; }
		
		//DELIMITER?
		public RuleCall getDELIMITERTerminalRuleCall_2() { return cDELIMITERTerminalRuleCall_2; }
	}
	public class EndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.End");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cSvalAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSvalINTTerminalRuleCall_2_0 = (RuleCall)cSvalAssignment_2.eContents().get(0);
		private final Keyword cGKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cWSTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cGvalAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cGvalINTTerminalRuleCall_5_0 = (RuleCall)cGvalAssignment_5.eContents().get(0);
		private final Keyword cDKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final RuleCall cWSTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Assignment cDvalAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDvalINTTerminalRuleCall_8_0 = (RuleCall)cDvalAssignment_8.eContents().get(0);
		private final Keyword cPKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final RuleCall cWSTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		private final Assignment cPvalAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cPvalINTTerminalRuleCall_11_0 = (RuleCall)cPvalAssignment_11.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_12 = (RuleCall)cGroup.eContents().get(12);
		private final Keyword cTKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final RuleCall cWSTerminalRuleCall_14 = (RuleCall)cGroup.eContents().get(14);
		private final Assignment cTvalAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cTvalINTTerminalRuleCall_15_0 = (RuleCall)cTvalAssignment_15.eContents().get(0);
		
		//End:
		//	'S' WS? sval=INT 'G' WS? gval=INT 'D' WS? dval=INT 'P' WS? pval=INT WS 'T' WS? tval=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'S' WS? sval=INT 'G' WS? gval=INT 'D' WS? dval=INT 'P' WS? pval=INT WS 'T' WS? tval=INT
		public Group getGroup() { return cGroup; }
		
		//'S'
		public Keyword getSKeyword_0() { return cSKeyword_0; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_1() { return cWSTerminalRuleCall_1; }
		
		//sval=INT
		public Assignment getSvalAssignment_2() { return cSvalAssignment_2; }
		
		//INT
		public RuleCall getSvalINTTerminalRuleCall_2_0() { return cSvalINTTerminalRuleCall_2_0; }
		
		//'G'
		public Keyword getGKeyword_3() { return cGKeyword_3; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_4() { return cWSTerminalRuleCall_4; }
		
		//gval=INT
		public Assignment getGvalAssignment_5() { return cGvalAssignment_5; }
		
		//INT
		public RuleCall getGvalINTTerminalRuleCall_5_0() { return cGvalINTTerminalRuleCall_5_0; }
		
		//'D'
		public Keyword getDKeyword_6() { return cDKeyword_6; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_7() { return cWSTerminalRuleCall_7; }
		
		//dval=INT
		public Assignment getDvalAssignment_8() { return cDvalAssignment_8; }
		
		//INT
		public RuleCall getDvalINTTerminalRuleCall_8_0() { return cDvalINTTerminalRuleCall_8_0; }
		
		//'P'
		public Keyword getPKeyword_9() { return cPKeyword_9; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_10() { return cWSTerminalRuleCall_10; }
		
		//pval=INT
		public Assignment getPvalAssignment_11() { return cPvalAssignment_11; }
		
		//INT
		public RuleCall getPvalINTTerminalRuleCall_11_0() { return cPvalINTTerminalRuleCall_11_0; }
		
		//WS
		public RuleCall getWSTerminalRuleCall_12() { return cWSTerminalRuleCall_12; }
		
		//'T'
		public Keyword getTKeyword_13() { return cTKeyword_13; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_14() { return cWSTerminalRuleCall_14; }
		
		//tval=INT
		public Assignment getTvalAssignment_15() { return cTvalAssignment_15; }
		
		//INT
		public RuleCall getTvalINTTerminalRuleCall_15_0() { return cTvalINTTerminalRuleCall_15_0; }
	}
	public class StartLineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.startLine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final Keyword cSKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cWSTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cENDLINETerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//startLine:
		//	(STRING | WS)* 'S' WS? INT ENDLINE;
		@Override public ParserRule getRule() { return rule; }
		
		//(STRING | WS)* 'S' WS? INT ENDLINE
		public Group getGroup() { return cGroup; }
		
		//(STRING | WS)*
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0_0() { return cSTRINGTerminalRuleCall_0_0; }
		
		//WS
		public RuleCall getWSTerminalRuleCall_0_1() { return cWSTerminalRuleCall_0_1; }
		
		//'S'
		public Keyword getSKeyword_1() { return cSKeyword_1; }
		
		//WS?
		public RuleCall getWSTerminalRuleCall_2() { return cWSTerminalRuleCall_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//ENDLINE
		public RuleCall getENDLINETerminalRuleCall_4() { return cENDLINETerminalRuleCall_4; }
	}
	
	
	private final IGESElements pIGES;
	private final StartElements pStart;
	private final GlobalElements pGlobal;
	private final DataElements pData;
	private final EntryElements pEntry;
	private final ParametersElements pParameters;
	private final PEntryElements pPEntry;
	private final PMultiEntryElements pPMultiEntry;
	private final ValueElements pValue;
	private final HStringElements pHString;
	private final ParamElements pParam;
	private final PointerElements pPointer;
	private final EndElements pEnd;
	private final StartLineElements pStartLine;
	private final TerminalRule tINT;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tHOLLERITH;
	private final TerminalRule tSTRING;
	private final TerminalRule tWS;
	private final TerminalRule tENDLINE;
	private final TerminalRule tDELIMITER;
	private final TerminalRule tSEPARATER;
	
	private final Grammar grammar;

	@Inject
	public IGESGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pIGES = new IGESElements();
		this.pStart = new StartElements();
		this.pGlobal = new GlobalElements();
		this.pData = new DataElements();
		this.pEntry = new EntryElements();
		this.pParameters = new ParametersElements();
		this.pPEntry = new PEntryElements();
		this.pPMultiEntry = new PMultiEntryElements();
		this.pValue = new ValueElements();
		this.pHString = new HStringElements();
		this.pParam = new ParamElements();
		this.pPointer = new PointerElements();
		this.pEnd = new EndElements();
		this.pStartLine = new StartLineElements();
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.INT");
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.DOUBLE");
		this.tHOLLERITH = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.HOLLERITH");
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.STRING");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.WS");
		this.tENDLINE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.ENDLINE");
		this.tDELIMITER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.DELIMITER");
		this.tSEPARATER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.january.geometry.xtext.IGES.SEPARATER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.january.geometry.xtext.IGES".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//IGES:
	//	start=Start
	//	global=Global
	//	data=Data
	//	parameters=Parameters
	//	end=End;
	public IGESElements getIGESAccess() {
		return pIGES;
	}
	
	public ParserRule getIGESRule() {
		return getIGESAccess().getRule();
	}
	
	//Start:
	//	lines+=startLine+;
	public StartElements getStartAccess() {
		return pStart;
	}
	
	public ParserRule getStartRule() {
		return getStartAccess().getRule();
	}
	
	//Global:
	//	{Global} (values+=Value* WS? 'G' WS? INT ENDLINE)+
	//	values+=Value* SEPARATER WS? 'G' WS? INT ENDLINE;
	public GlobalElements getGlobalAccess() {
		return pGlobal;
	}
	
	public ParserRule getGlobalRule() {
		return getGlobalAccess().getRule();
	}
	
	//Data:
	//	entries+=Entry+;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//Entry:
	//	WS type=INT WS? paramData=INT WS? structure=INT WS? lineFont=INT WS? level=INT WS? view=INT WS? TransformMatrix=INT
	//	WS? INT? WS? status=INT 'D' WS? index=INT ENDLINE
	//	WS? INT WS? lineWeight=INT WS? color=INT WS? paramLines=INT WS? form=INT WS? entityLabel=STRING? WS? subNum=INT 'D'
	//	WS? INT ENDLINE;
	public EntryElements getEntryAccess() {
		return pEntry;
	}
	
	public ParserRule getEntryRule() {
		return getEntryAccess().getRule();
	}
	
	//Parameters:
	//	entries+=(PMultiEntry | PEntry)+;
	public ParametersElements getParametersAccess() {
		return pParameters;
	}
	
	public ParserRule getParametersRule() {
		return getParametersAccess().getRule();
	}
	
	//PEntry:
	//	type=INT
	//	values+=Value* SEPARATER WS? dIndex=INT 'P' WS? indicies+=INT ENDLINE;
	public PEntryElements getPEntryAccess() {
		return pPEntry;
	}
	
	public ParserRule getPEntryRule() {
		return getPEntryAccess().getRule();
	}
	
	//PMultiEntry PEntry:
	//	(values+=Value* WS? dIndex=INT 'P' WS? indicies+=INT ENDLINE)+
	//	values+=Value* SEPARATER WS? INT 'P' WS? INT ENDLINE
	public PMultiEntryElements getPMultiEntryAccess() {
		return pPMultiEntry;
	}
	
	public ParserRule getPMultiEntryRule() {
		return getPMultiEntryAccess().getRule();
	}
	
	//Value:
	//	Param | Pointer | HString;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//HString:
	//	DELIMITER? val=HOLLERITH DELIMITER?;
	public HStringElements getHStringAccess() {
		return pHString;
	}
	
	public ParserRule getHStringRule() {
		return getHStringAccess().getRule();
	}
	
	//Param:
	//	DELIMITER? val=DOUBLE DELIMITER?;
	public ParamElements getParamAccess() {
		return pParam;
	}
	
	public ParserRule getParamRule() {
		return getParamAccess().getRule();
	}
	
	//Pointer:
	//	DELIMITER? val=INT DELIMITER?;
	public PointerElements getPointerAccess() {
		return pPointer;
	}
	
	public ParserRule getPointerRule() {
		return getPointerAccess().getRule();
	}
	
	//End:
	//	'S' WS? sval=INT 'G' WS? gval=INT 'D' WS? dval=INT 'P' WS? pval=INT WS 'T' WS? tval=INT;
	public EndElements getEndAccess() {
		return pEnd;
	}
	
	public ParserRule getEndRule() {
		return getEndAccess().getRule();
	}
	
	//startLine:
	//	(STRING | WS)* 'S' WS? INT ENDLINE;
	public StartLineElements getStartLineAccess() {
		return pStartLine;
	}
	
	public ParserRule getStartLineRule() {
		return getStartLineAccess().getRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return tINT;
	}
	
	//terminal DOUBLE:
	//	('+' | '-')? INT '.' INT? (('e' | 'E') ('+' | '-')? INT)?;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal HOLLERITH:
	//	INT 'H' .;
	public TerminalRule getHOLLERITHRule() {
		return tHOLLERITH;
	}
	
	//terminal STRING:
	//	'A..Z' | 'a'..'z' | '0'..'9' | '"'+;
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r'+;
	public TerminalRule getWSRule() {
		return tWS;
	}
	
	//terminal ENDLINE:
	//	'\r'? '\n';
	public TerminalRule getENDLINERule() {
		return tENDLINE;
	}
	
	//terminal DELIMITER:
	//	',';
	public TerminalRule getDELIMITERRule() {
		return tDELIMITER;
	}
	
	//terminal SEPARATER:
	//	';';
	public TerminalRule getSEPARATERRule() {
		return tSEPARATER;
	}
}
