/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.january.geometry.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class IGESProposalProvider extends AbstractIGESProposalProvider {
}
