/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.january.geometry.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIGESScopeProvider extends DelegatingScopeProvider {
}
