/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.january.geometry.xtext.tests

import com.google.inject.Inject
import org.eclipse.january.geometry.xtext.iGES.IGES
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(IGESInjectorProvider)
class IGESParsingTest{

	@Inject
	ParseHelper<IGES> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''                        ffff     dddd                                   S      1
S      1G      4D     12P      6                                        T      1''')
		System.out.println("Done")
		Assert.assertNotNull(result)

		System.out.println(result.start)
		System.out.println(result.end)

		//System.out.println(result.data.entities)
		
		//System.out.println(result.scount)
		//System.out.println(result.gcount)
		//System.out.println(result.dcount)
		//System.out.println(result.pcount)
		//System.out.println(result.tcount)
		
	}
	

}
